modLoader="javafml"
loaderVersion="[42,)"
license="MIT"

[[mods]]
modId="bsvsb"
version="${version}"
displayName="Better Rubidium Video Settings"
logoFile="icon.png"
credits="LimeShulkerBox,TexTrue"
authors="TexTrueStudio"
description='''
Changes the Sodium Forge Port Video settings back to the original,
You can get to the Sodium Forge Port Video Settings page via the Vanilla video settings page.
'''

[[dependencies.bsvsb]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bsvsb]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.bsvsb]]
modId = "rubidium"
mandatory = true
versionRange = "[0.6,)"
ordering = "NONE"
side = "CLIENT"